{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mysql.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.mysql.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mysql.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.mysql.name }}
    spec:
      containers:
        - name: {{ .Values.mysql.name }}
          image: {{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}
          env:
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.user }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.password }}
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.rootPassword }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
          volumeMounts:
            - name: review-db-data
              mountPath: /var/lib/mysql
            - name: init-db
              mountPath: /docker-entrypoint-initdb.d
          livenessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p{{ .Values.mysql.rootPassword }}"]
            initialDelaySeconds: {{ .Values.mysql.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql.livenessProbe.periodSeconds }}
          readinessProbe:
            exec:
              command: ["mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-p{{ .Values.mysql.rootPassword }}"]
            initialDelaySeconds: {{ .Values.mysql.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.mysql.readinessProbe.periodSeconds }}
      volumes:
        - name: review-db-data
          persistentVolumeClaim:
            claimName: {{ .Values.mysql.pvc.name }}
        - name: init-db
          configMap:
            name: {{ .Values.initScripts.name }}
{{- end }}

